### ISSUE TITLE
Atomic transfers - Invalid Input: Unable to parse transaction

### ISSUE THREAD

**Issue by hutch120** [perawallet/connect#10]
Hi All, Is anyone having an issue with signing transactions that are part of an atomic transfer?

We have a group of four transactions (grouped using assignGroupID). Two of the transactions are to be signed by the "client" and the other two by the "agent". This works on MyAlgo, but similar code fails on PeraWallet.

I'm getting this error message:

```
PeraWalletConnectError: Invalid Input: Unable to parse transaction
```

This is the transaction I'm asking the client to sign, note it has a group field. Without the group field it works. To be clear, this uses the `algosdk.assignGroupID(txns)` to assign the group field. https://developer.algorand.org/docs/get-details/atomic_transfers/#group-transactions

```
assetIndex: 95739847
fee: 1000
firstRound: 22266222
from: {publicKey: Uint8Array(32), checksum: Uint8Array(4)}
genesisHash: Uint8Array(32) [72, 99, 181, 24, 164, 179, 200, 78, 200, 16, 242, 45, 79, 16, 129, 203, 15, 113, 240, 89, 167, 172, 32, 222, 198, 47, 127, 112, 229, 9, 58, 34, buffer: ArrayBuffer(32), byteLength: 32, byteOffset: 0, length: 32, Symbol(Symbol.toStringTag): 'Uint8Array']
genesisID: "testnet-v1.0"
group: Uint8Array(32) [52, 22, 127, 120, 101, 143, 0, 37, 1, 250, 209, 68, 190, 12, 254, 233, 127, 7, 150, 28, 123, 9, 3, 130, 49, 244, 184, 29, 75, 239, 195, 133, buffer: ArrayBuffer(32), byteLength: 32, byteOffset: 0, length: 32, Symbol(Symbol.toStringTag): 'Uint8Array']
lastRound: 22267222
lease: Uint8Array [buffer: ArrayBuffer(0), byteLength: 0, byteOffset: 0, length: 0, Symbol(Symbol.toStringTag): 'Uint8Array']
name: "Transaction"
note: Uint8Array(5) [111, 112, 116, 105, 110, buffer: ArrayBuffer(5), byteLength: 5, byteOffset: 0, length: 5, Symbol(Symbol.toStringTag): 'Uint8Array']
tag: Uint8Array(2) [84, 88, buffer: ArrayBuffer(2), byteLength: 2, byteOffset: 0, length: 2, Symbol(Symbol.toStringTag): 'Uint8Array']
to: {publicKey: Uint8Array(32), checksum: Uint8Array(4)}
type: "axfer"
```

Note there is an incomplete thread about this on discord `Pera wallet` server, search for `PeraWalletConnectError: Invalid Input: Unable to parse transaction` or use this link https://discord.com/channels/933650374601080842/943046789785849896/975775093319925821

Sample code here to build a grouped transaction (note this code is very similar to how we generate the transactions.)
https://gist.github.com/mucahit/1397ff190ca815af2a856360e22467ea

The transaction can be signed by MyAlgo, code looks like this:

```
const myAlgoWallet = await getMyAlgo()
const txns = [
  Uint8Array.from(txnData?.optInTxnEnc ?? []),
  Uint8Array.from(txnData?.paymentTxnEnc ?? [])
]
const signedClientTxns = await myAlgoWallet.signTransaction(txns)
optInSignedTxnNArr = Array.from(signedClientTxns[0].blob)
paymentSignedTxnNArr = Array.from(signedClientTxns[1].blob)
// Note there are two more transactions in the group that are signed by other parties (the agent)
```

This is our attempt for Pera which results in the error mentioned.

```
const myPeraWallet = getPeraWallet()
const optInTxn = Uint8Array.from(txnData?.optInTxnEnc ?? [])
const decodedOptIn = algosdk.decodeUnsignedTransaction(optInTxn)
const paymentTxn = Uint8Array.from(txnData?.paymentTxnEnc ?? [])
const decodedPayment = algosdk.decodeUnsignedTransaction(paymentTxn)
let signedClientTxns = [new Uint8Array(1), new Uint8Array(2)]
// myPeraWallet.signTransaction throws "PeraWalletConnectError: Invalid Input: Unable to parse transaction"
signedClientTxns = await myPeraWallet.signTransaction([
  [
    { txn: decodedOptIn },
    { txn: decodedPayment }
  ]
])
optInSignedTxnNArr = Array.from(signedClientTxns[0])
paymentSignedTxnNArr = Array.from(signedClientTxns[1])
// Note there are two more transactions in the group that are signed by other parties (the agent)
```

**Comment by hutch120** [comment]
Bump, any thoughts?

**Comment by hutch120** [comment]
Not sure it is clear from the code snippet above, but might be important to mention, there are four transactions in the group. We want the client to sign two of them and the other two are signed by the agent.

**Comment by hutch120** [comment]
That would defeat the purpose of an atomic transfer.

**Comment by hutch120** [comment]
@lions-wrinkle commented on Discord the following:

```
const transactions = [tx1, tx2, tx3, tx4];
algosdk.assignGroupID(transactions);
const transactionsToSign = [tx2, tx3, tx4];
const transactionsToSignPera = transactionsToSign.map(tx => ({ txn: tx }))
signedTransactions = await wallet.signTransaction([transactionsToSignPera]);
```

This is a cut down version of my code which seems equivalent?

```
import algosdk from 'algosdk';
import { PeraWalletConnect } from '@perawallet/connect';
const wallet = new PeraWalletConnect();
const txnUint8 = Uint8Array.from(txnNumberArray) // Decoding one of the grouped transactions from a JSON Number Array to Uint8 (needed to pass as JSON)
const algoTxnObj = algosdk.decodeUnsignedTransaction(txnUint8) // Converting Uint8 to Algo Transaction Object
signedClientTxns = await wallet.signTransaction([[{ txn: algoTxnObj }]]) // Attempting to sign one of the grouped txns which throws Parse error.
```

**Comment by hutch120** [comment]
Ah, ok, had another chat on Discord (thanks @lion-wrinkle), and wanted to get this written down so we don't loose this in the Discord thread. I haven't tried this yet, but it is starting to make sense.

It appears that PeraWallet wants us to send all the transactions in the group to the wallet, even those that don't need to be signed. Maybe to show the client? In any case, there is a second parameter on the object passed to `perawallet.signTransaction` that specifies the signer(s) which I assume we can set to the connected wallet for a subset of the transactions.

hutcho — Today at 16:44
Oh... hold on... I think I get it...
Each txn is an object that you add the signer
[{ txn: txn1, signer: client }, { txn: txn2: signer: client }, {txn: txn3, signer: agent }]

lions-wrinkle — Today at 16:49
I think it requires all the transactions from the group so it can present it to the user. This way, the user knows the complete series of events that will happen, even though he don’t need to sign all the transactions.

I'm away for a week... but will try this when I get back.

**Comment by luazhizhan** [comment]
I have found the solution to this issue. We have to send Pera all the transactions of the group even the ones that are signed by the agent already. This is how I did it.

```js
const transactionsGroup = [tx1, tx2, tx3, tx4]; // say tx2 and tx4 are signed transactions
algosdk.assignGroupID(transactionsGroup);

const transactionsToSign = [
  {
    txn: tx1,
    signers: [algosdk.encodeAddress(tx.from.publicKey)],
  },
  {
    txn: tx2.txn, // Send the signed transaction
    signers: [], // Empty singers for transaction that does not need to be signed
  },
  {
    txn: tx3,
    signers: [algosdk.encodeAddress(tx.from.publicKey)],
  },
  {
    txn: tx4.txn, // Send the signed transaction
    signers: [], // Empty singers for transaction that does not need to be signed
  },
];

try {
  const signedTransactions = await wallet.signTransaction(
    [transactionsToSign],
    currentWalletAddress
  )
} catch (err) {
  console.log(err)
}
```

**Comment by hutch120** [comment]
I finally got back to this, and I can confirm @luazhizhan solution works. Some code extracts below for clarity on our solution.

Server code looks something like this: (note that the txnData transactions are encoded as number arrays so they can be added to a JSON payload.)

```
const txns = [optInTxn, paymentTxn, transferTxn]
let txgroup = algosdk.assignGroupID(txns)
const optInTxnEnc = Array.from(algosdk.encodeUnsignedTransaction(txgroup[0]))
const paymentTxnEnc = Array.from(algosdk.encodeUnsignedTransaction(txgroup[1]))
var mintAccount= algosdk.mnemonicToSecretKey(MINT_PHRASE)
const transferSignedTxn = Array.from(txgroup[2].signTxn(mintAccount.sk))
const txnData = {
  optInTxnEnc, // To be signed by user
  paymentTxnEnc, // To be signed by user
  transferSignedTxn // To be returned by user unsigned and signed by treasury
}
```

Then the client code looks something like this:

```
import algosdk from 'algosdk'
import { PeraWalletConnect } from '@perawallet/connect'

const peraWallet = new PeraWalletConnect()
const accountAddress = peraWallet.connector?.accounts[0]

const decodedOptIn = algosdk.decodeUnsignedTransaction(
  Uint8Array.from(txnData.optInTxnEnc)
)
const decodedPayment = algosdk.decodeUnsignedTransaction(
  Uint8Array.from(txnData.paymentTxnEnc)
)
const decodedTransfer = algosdk.decodeSignedTransaction(
  Uint8Array.from(txnData.transferSignedTxnEnc)
)

let signedClientTxns: Uint8Array[] = await peraWallet.signTransaction([[
  { 
    txn: decodedOptIn, 
    signers: [algosdk.encodeAddress(decodedOptIn.from.publicKey)]
  },
  { 
    txn: decodedPayment, 
    signers: [algosdk.encodeAddress(decodedPayment.from.publicKey)]
  },
  { 
    txn: decodedTransfer.txn, // << Key to success is the .txn on the end of the signed txn. 
    signers: [] // Also, this does not need to be signed.
  }
]])

const optInSignedTxnNArr: number[] = optInSignedTxnNArr = Array.from(signedClientTxns[0])
const paymentSignedTxnNArr: number[] = Array.from(signedClientTxns[1])
const transferSignedTxnNArr: number[] = txnData.transferSignedTxnEnc

const txnDataSigned = {
  optInSignedTxnNArr,
  paymentSignedTxnNArr,
  transferSignedTxnNArr
}
```

**Comment by 1forh** [comment]
@hutch120 This was incredibly helpful!! Thank you!

**Comment by oravix** [comment]
> I have found the solution to this issue. We have to send Pera all the transactions of the group even the ones that are signed by the agent already. This is how I did it.
> 
> ```js
> const transactionsGroup = [tx1, tx2, tx3, tx4]; // say tx2 and tx4 are signed transactions
> algosdk.assignGroupID(transactionsGroup);
> 
> const transactionsToSign = [
>   {
>     txn: tx1,
>     signers: [algosdk.encodeAddress(txn1.from.publicKey)],
>   },
>   {
>     txn: tx2.txn, // Send the signed transaction
>     signers: [], // Empty singers for transaction that does not need to be signed
>   },
>   {
>     txn: tx3,
>     signers: [algosdk.encodeAddress(txn3.from.publicKey)],
>   },
>   {
>     txn: tx4.txn, // Send the signed transaction
>     signers: [], // Empty singers for transaction that does not need to be signed
>   },
> ];
> 
> try {
>   const signedTransactions = await wallet.signTransaction(
>     [transactionsToSign],
>     currentWalletAddress
>   )
> } catch (err) {
>   console.log(err)
> }
> ```

Sorry, but groupID has to be assigned only on unsigned transactions, right? Or i can create an opt-in tx on user side and then i can transfer it on BE to add it to a group, assigning a group ID and sending to the network? Thank you.
