### ISSUE TITLE
Asset config tx incorrectly identified as destroy asset tx

### ISSUE THREAD

**Issue by stein-f** [perawallet/connect#105]
Hi, the transaction summary view is incorrectly identifying asset config transactions as destroy asset transactions - pretty scary 😆 

The mobile app doesn't have the same issue and labels it as a asset config tx

<img width="703" alt="Screenshot 2023-01-18 at 22 54 22" src="https://user-images.githubusercontent.com/96784685/213315454-656365b7-40a0-4171-92ca-e66ddb7d8d92.png">

![Screenshot_20230118-225627](https://user-images.githubusercontent.com/96784685/213315644-a1b215fd-0319-4cfa-ad6d-83dbec7989af.png)

**Comment by yigiterdev** [comment]
Thank you @stein-f! We are currently investigating this problem.

**Comment by yigiterdev** [comment]
Hey @stein-f,
We released new version of web wallet. Can you confirm if the problem is solved or not?

**Comment by stein-f** [comment]
Hey @yigiterdev 

Yes this looks correct now.

Many thanks!

**Comment by yigiterdev** [comment]
Thank you for you report!
