### ISSUE TITLE
Await instead of then when initializing Pera

### ISSUE THREAD

**Issue by bigbulb** [perawallet/connect#108]
Hello,

In the doc, to Create handler methods for Pera Wallet connection, it is suggested to use a Promise with .then:

```
function handleConnectWalletClick() {
    peraWallet
      .connect()
      .then((newAccounts) => {
        // Setup the disconnect event listener
        peraWallet.connector?.on("disconnect", handleDisconnectWalletClick);

        setAccountAddress(newAccounts[0]);
      })
      .reject((error) => {
        // You MUST handle the reject because once the user closes the modal, peraWallet.connect() promise will be rejected.
        // For the async/await syntax you MUST use try/catch
        if (error?.data?.type !== "CONNECT_MODAL_CLOSED") {
          // log the necessary errors
        }
      });
  }
```

Current issue is that I would like to return the _newAccounts_ variable to be used in other part of the code and files. Is there an easy way to use await/async instead?
I tried the following but _accounts_ is considered as _void_ so I don't have a way to retrieve it.

```
await peraWallet.connect();
const accounts = await peraWallet.connector?.on("disconnect", handleDisconnectWalletClick);
return accounts;
```
If anyone has any suggestion, feel free to comment.

**Comment by MacroChip** [comment]
```
try {
  const accounts = await peraWallet.connect();
  setAccountAddress(accounts[0]);
  peraWallet.connector?.on("disconnect", handleDisconnectWalletClick);
} catch (e) {
  // You MUST handle the reject because once the user closes the modal, peraWallet.connect() promise will be rejected.
  // For the async/await syntax you MUST use try/catch
  if (error?.data?.type !== "CONNECT_MODAL_CLOSED") {
    // log the necessary errors
  }
}
```
Is equivalent code. This is what the comment in the example code was implying about "For the async/await syntax you MUST use try/catch". If you wish, you may declare `let accounts` outside of the try block then have `accounts = await peraWallet.connect();` inside the try block. This means that accounts will be defined if the user completes the connect before closing the modal.

**Comment by bigbulb** [comment]
Resolved. Thanks @MacroChip
