### ISSUE TITLE
QrCode Styling - self is not defined

### ISSUE THREAD

**Issue by satriad1st** [perawallet/connect#146]
after updating perawallet into version 1.3.0, i got the error from qr-code-styling : 

![Screenshot 2023-07-14 at 13 02 15](https://github.com/perawallet/connect/assets/30196977/fc2eed8a-6ec0-44aa-9ab7-49beec02dec5)

**Comment by hajirasyafi** [comment]
please update to version 1.3.1,

**Comment by satriad1st** [comment]
> please update to version 1.3.1,

cool, thanks it's worked..

**Comment by hajirasyafi** [comment]
sama2 bro
