### ISSUE TITLE
Unable to connect using Svelte

### ISSUE THREAD

**Issue by plasmatech8** [perawallet/connect#2]
I have been struggling to get both WalletConnect and Pera Wallet connect to work using SvelteKit.

In Pera wallet, it gives me a `navigator not defined` error. 

Is this library framework agnostic?

Also note that using the WalletConnect libraries I get the error: `ws does not work in the browser. Browser clients must use the native WebSocket object`.

## Steps

Initialize SvelteKit app and install Pera wallet library.
```bash
npm init svelte my-app
cd my-app
npm install
npm install -D @perawallet/connect
npm run dev
```

Create demo Svelte component.
```svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { PeraWalletConnect } from '@perawallet/connect';

	const peraWallet = new PeraWalletConnect();
	let accountAddress: string | null;
	let isConnectedToPeraWallet = false;

	onMount(() => {
		// Reconnect to the session when the component is mounted
		peraWallet.reconnectSession().then((accounts) => {
			// Setup the disconnect event listener
			peraWallet.connector?.on('disconnect', handleDisconnectWalletClick);
			if (accounts.length) {
				accountAddress = accounts[0];
			}
		});
	});

	function handleConnectWalletClick() {
		peraWallet.connect().then((newAccounts: string[]) => {
			// Setup the disconnect event listener
			peraWallet.connector?.on('disconnect', handleDisconnectWalletClick);
			accountAddress = newAccounts[0];
		});
	}

	function handleDisconnectWalletClick() {
		peraWallet.disconnect();
		accountAddress = null;
	}
</script>

<button onClick={isConnectedToPeraWallet ? handleDisconnectWalletClick : handleConnectWalletClick}>
	{isConnectedToPeraWallet ? 'Disconnect' : 'Connect to Pera Wallet'}
</button>

```

Response:
```
navigator is not defined

ReferenceError: navigator is not defined
    at w (/Users/.../my-app/node_modules/@perawallet/connect/dist/index.js:16:4545)
    at Object.<anonymous> (/Users/.../my-app/node_modules/@perawallet/connect/dist/index.js:16:4647)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1151:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:168:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:197:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
```

**Comment by mucahit** [comment]
Hey @plasmatech8, thanks for the detailed report. 

Yes, `@perawallet/connect` is framework agnostic, but it uses some browser JavaScript features such as `navigator`. In this case, `svelte` tries to run it on the server-side but `navigator` doesn't exist on the server-side JavaScript.

So, as suggested in the official documentation of the Svelte, you can dynamically import `@perawallet/connect`, which requires to run on the client-side. https://sapper.svelte.dev/docs#Third-party_libraries_that_depend_on_window

`index.svelte`
```svelte
<script>
  import { onMount } from 'svelte';

  let PeraConnectButton;
  let peraWallet;

  onMount(async () => {
    // pollyfill for `global`
    window.global = window;

    PeraConnectButton = (await import('$lib/PeraConnectButton.svelte')).default;
    peraWallet = (await import('$lib/peraWallet')).default;
  });
</script>

<div>
  <svelte:component this={PeraConnectButton}/>
</div>
```

`PeraConnectButton.svelte` -> https://gist.github.com/mucahit/41950dbcdf7d498809dffe79edf8ea36
`peraWallet.ts` -> https://gist.github.com/mucahit/3fb142e076b76f03681512afaa386a10

I hope that helps.

**Comment by plasmatech8** [comment]
Thanks @mucahit 

The component appears to be failing to load for me. Note that I am using SvelteKit, not Sapper.

![image](https://user-images.githubusercontent.com/40431112/170230672-157ed4ce-87ee-4e95-b028-cfceb8682685.png)

I have seen this kind of workaround before, but the thought hadn't come to me :) 

I am trying to figure out a nice way to load the package in a typescript module containing a wallet object, but it looks like I am going to have to find a way to loop it around client side using the method you mentioned.

**Comment by plasmatech8** [comment]
Thanks, I have managed to find a way to do it that I like a lot.

```ts
// For type definitions
import type { PeraWalletConnect } from '@perawallet/connect';

// In an initialization function of a class/object
const PeraWalletConnect = (await import('@perawallet/connect')).PeraWalletConnect;
this.client = new PeraWalletConnect();
```
