### ISSUE TITLE
Library is not SSR compatible (NextJS etc)

### ISSUE THREAD

**Issue by dbateman** [perawallet/connect#20]
This can't be used in NextJS without using a dynamic import (not great for typing etc) as we get `navigator is not defined` when a page is statically rendered. Please can you check for a browser context and make the code safe for SSR?

**Comment by dbateman** [comment]
Oh - now i see this has been reported before, in issue #6. If this is largely an issue with dependencies, maybe we can get a separate type dec for the `PeraWalletConnect` class (an interface) that can be imported without causing this issue. Dynamic imports aren't friendly with typechdcking outside of the scope of the import.

**Comment by mucahit** [comment]
Hey @dbateman, thanks for the feedback. 

Yes, we'll change the structure slightly to support SSR soon.

**Comment by mucahit** [comment]
Hey @dbateman, we have better SSR support with the `0.1.6` version. https://github.com/perawallet/connect/releases/tag/0.1.6
