### ISSUE TITLE
Problem with connecting to wallet in Vite

### ISSUE THREAD

**Issue by windrunnerdev** [perawallet/connect#4]
as soon as I call `connect `method, it crashes.

code snippet:

```
try {
    const peraWallet = new PeraWalletConnect()
    const accounts = await peraWallet.connect()
    if (accounts.length > 0) {
        setAccountAddress(accounts[0])
    }
} catch (error_: any) {
    handleError(error_.message)
}
```
thrown error:

```
{
    "name": "PeraWalletConnectError",
    "data": {
        "type": "SESSION_CONNECT",
        "detail": {}
    },
    "message": "ws does not work in the browser. Browser clients must use the native WebSocket object"
}
```

Development environment:
Vite version: `2.7.2`
node version: `v14.18.1`, `v16`

**Comment by mucahit** [comment]
Hey, @windrunnerdev any chance you could provide a codesandbox repro?

**Comment by hutch120** [comment]
We migrated to Create React App instead, pls close.

**Comment by aorumbayev** [comment]
@mucahit this issue is still pretty much in place - its caused by wallet connect dependency. Pick any vite starter project (vue for example), and you'll hit this error with `ws` being unavailable in browser. If ill get some time i can setup a codesandbox but once again - its very easy to replicate

**Comment by mucahit** [comment]
Hello, we couldn't find any workarounds to solve this issue with Vite 2.x and Vite 3.x. **The only solution seems to upgrade to Vite 4.x**

**Comment by guanzo** [comment]
Still happening with `"vite": "^5.0.10",`
