### ISSUE TITLE
QQ: signing arbitrary data

### ISSUE THREAD

**Issue by nikitaeverywhere** [perawallet/connect#42]
Hello! Today I came across the fact that not all Algorand wallets (Pera included) support signing arbitrary (or structured) data.

In our application it is very critical to verify the ownership of the address without sending the transactions to the chain. Is there any way we can do it in Pera?

For instance, MyAlgo supports signing custom data.

Thanks!

**Comment by lionDEVa** [comment]
Talk to Cardano Support on the [ALGO Live support](https://algorrand-dev.com) so that your issue can be looked into.

**Comment by ZitRos** [comment]
I think the problem that signing standard [exists](https://developer.algorand.org/articles/verify-signatures-and-signed-data-within-algorand-smart-contracts/), but it's not implemented in Pera Wallet. Hence I believe I asked about it in the right place.

**Comment by adshodgson** [comment]
@ZitRos Did you ever find a work around to this?

**Comment by ZitRos** [comment]
Nope. That's the question for the Pera Wallet team, they can implement it, but they don't do it. 

CC @mucahit can you try bringing anyone relevant to this discussion? Or should I open it somewhere else?

**Comment by yasincaliskan** [comment]
Hello @nikitaeverywhere , Pera Wallet can now sign arbitrary data on Android and iOS. Did you have a chance to check?

**Comment by nikitaeverywhere** [comment]
Hello @yasincaliskan! Happy to hear it finally landed. By the time we finished that project, so I doubt I can test it now. However I can give some feedback on the API if you share one.

**Comment by yasincaliskan** [comment]
We added an example to the README file. You can also test it on the demo app. Please check it out https://github.com/perawallet/pera-demo-dapp @nikitaeverywhere

**Comment by nikitaeverywhere** [comment]
Readme looks good - thanks. I will close the issue now.

From the dApp side, make sure there's a meaningful way to detect whether older Pera version support signing.
