### ISSUE TITLE
Modal appears behind elements

### ISSUE THREAD

**Issue by gabrielkuettel** [perawallet/connect#5]
The connect modal appears behind positioned elements elements with a defined `z-index` (see screenshot below).

<img width="833" alt="Screen Shot 2022-06-07 at 00 35 22" src="https://user-images.githubusercontent.com/40471143/172304392-2bb5d118-1d14-4e0e-a7f1-affd33cd3b6d.png">

I'm overriding the `pera-wallet-connect-modal` css class and providing a higher `z-index` as a workaround, but that might not work in all situations. Would be ideal if the modal component used a react portal to escape the stacking context.

**Comment by mucahit** [comment]
Hey, @yigiterdev let's check this if it's still happening. Thanks!

**Comment by seanpatches** [comment]
Still occurring, I added a styling override to my index.html

`    <style>
      .pera-wallet-connect-modal {
        z-index: 999999 !important;
      }
     </style>
`

**Comment by mucahit** [comment]
Added details to the Readme https://github.com/perawallet/connect#customizing-style
