### ISSUE TITLE
`ReferenceError: navigator is not defined` during server-side build

### ISSUE THREAD

**Issue by gabrielkuettel** [perawallet/connect#6]
When using NextJS, the build throws an error because `navigator` is not defined on the server side. It seems this is being used to construct the modal deep link on iOS and Android, but is it possible not to rely on client side objects? We did not have this issue when using `algorand-walletconnect-qrcode-modal`.

**Comment by Vilijan** [comment]
I am struggling with the same error using NextJS.

@gabrielkuettel If you have found a way or workaround on how to use Pera with NextJS I would appreciate it if you can share it.

**Comment by gabrielkuettel** [comment]
> I am struggling with the same error using NextJS.
> 
> @gabrielkuettel If you have found a way or workaround on how to use Pera with NextJS I would appreciate it if you can share it.

Solved it using dynamic imports. This will only import it once it renders on the client side.

```
const PeraWalletConnect = (await import('@perawallet/connect')).PeraWalletConnect
const peraWallet = new PeraWalletConnect()
```

https://nextjs.org/docs/advanced-features/dynamic-import

**Comment by mucahit** [comment]
thanks, @gabrielkuettel! 

Currently, dynamic imports are the best option but we might change the structure to avoid using browser-based features with the upcoming releases.

**Comment by gabrielkuettel** [comment]
> thanks, @gabrielkuettel!
> 
> Currently, dynamic imports are the best option but we might change the structure to avoid using browser-based features with the upcoming releases.

Understood! Thanks.
