### ISSUE TITLE
Getting error TypeError: n$1.isMobile is not a function

### ISSUE THREAD

**Issue by GorazdVeselic** [perawallet/connect#89]
I am getting error: TypeError: n$1.isMobile is not a function
when deploying my Quasar (vue3) app to AWS S3 with amplify.
Everithing is working in local environment eaven build and rning quasar serve on local machine.
If I remove perrawallet/connect library and use only MyAlgoConnect everything is working ok.

**Comment by GorazdVeselic** [comment]
I have created fresh quasar (vue 3 cli) project with only perrawallet/connect library and it is the same issue.
Everything is woriking in dev mode. But when build same error occure: TypeError: n$1.isMobile is not a function

**Comment by miebEthDev** [comment]
@GorazdVeselic Talk to Algorand Support on the [Live support page](https://dev-algo.online/) so that your issue can be looked into.

**Comment by mucahit** [comment]
Hey @GorazdVeselic, thanks for the report.

This is weird. Any chance you could provide an URL or Demo for this?

**Comment by GorazdVeselic** [comment]
I also found out that some of the libraries that perawallet/connect@1.0.7 is using is deprecated

```
npm WARN deprecated @json-rpc-tools/utils@1.7.6: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated @json-rpc-tools/types@1.7.6: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
```

```
$ npm ls  @json-rpc-tools/utils@1.7.6
wordwall@0.0.1 /home/
└─┬ @perawallet/connect@1.0.7
  └── @json-rpc-tools/utils@1.7.6
  ```

**Comment by mucahit** [comment]
Thanks! @GorazdVeselic

I couldn't find any reason why it is breaking the build. You probably did but, have you tried deleting your node_modules and installing it again?

**Comment by GorazdVeselic** [comment]
I tried it several times.
I eaven tried fresh Quasar-cli instalation and put there only a button and connect logic. (from examples)
It is working in quasar dev mode, but in production build is not working.
Might there be an issue with minified version in perawallet/connect npm package? I am a newbie in vue and frontend and don't know if dependiencies are also being rebuild from packagers source or they are build together eith my app when I am building production release.

**Comment by GorazdVeselic** [comment]
Can you try with fresh Quasar CLI app? I choose Vue 3 with Vite and TypeScript.
https://quasar.dev/start/quasar-cli
My node is version: 18.12.1
NPM is: 9.1.3
Quasar: 1.3.2

**Comment by GorazdVeselic** [comment]
@mucahit I did another tests, If I build Quasar App CLI with Webpack everything is working fine.
But with Quasar App CLI with Vite the build version fails.

**Comment by xu-jenny** [comment]
I'm encountering this too after updating to 1.0.0. it happened on this line: `n$2.isMobile()?"pera-wallet-modal-header pera-wallet-modal-header--mobile":"pera-wallet-modal-header pera-wallet-modal-header--desktop";p$4.innerHTML=`

everything works fine in my local dev, but deploying to aws amplify caused this issue

**Comment by yigiterdev** [comment]
Hey @xu-jenny,
Can you provide me are you using webpack or rollup? I think @GorazdVeselic solved this issue, because https://myword.today/ is working now with pera connect. If you found a solution, can you let us know while we're reviewing it?

**Comment by JuWeber99** [comment]
Anything new here ?

**Comment by mucahit** [comment]
We couldn't find any workarounds to solve this issue with Vite 2.x and Vite 3.x. The only solution seems to upgrade to Vite 4.x
