### ISSUE TITLE
Getting `Missing or invalid topic field` on disconnect 

### ISSUE THREAD

**Issue by aorumbayev** [perawallet/connect#90]
Steps to replicate:

1. Navigate to next.js example https://codesandbox.io/s/perawallet-connect-next-js-demo-ryhbdb
2. Connect pera wallet
3. Click disconnect
4. Observe error 

Can be replicated in non sandbox example too. I believe some error is not handled correctly - it either needs to be passed higher in the stack or handled gracefully. 

In the current implementation, event if disconnect call is wrapped in try/catch error will still be thrown.

**Comment by mucahit** [comment]
Thanks @aorumbayev, will be fixed with the next release

**Comment by aorumbayev** [comment]
@mucahit I think it's actually a bug in the example I noticed that the disconnect is triggered twice because in the example same method is linked to on disconnect listener and tied to the button click. You just need to add if condition in the deactivate method to check if the client is connected before firing the disconnect.

Can open a PR if you think that's the case

**Comment by mucahit** [comment]
@aorumbayev It's also problematic on the core side. I believe we shouldn't allow disconnecting if there are no active sessions.

PR would be great @aorumbayev 🙏

**Comment by aorumbayev** [comment]
@mucahit here is the pr for the bug in the example https://github.com/perawallet/connect-examples/pull/3

**Comment by mucahit** [comment]
Perfect, thank you so much 👏  @aorumbayev
